### Get all projects
GET http://localhost:3000/api/projects

### Get a specific project by ID
GET http://localhost:3000/api/projects?id=1

### Create a new project
POST http://localhost:3000/api/projects
Content-Type: application/json

{
  "name": "RQL",
  "description": "A description for the new project"
}

### Get all topics
GET http://localhost:3000/api/topics

### Get a specific topic by ID
GET http://localhost:3000/api/topics?id=1

### Create a new topic
POST http://localhost:3000/api/topics
Content-Type: application/json

{
  "name": "Embedded"
}

### Protected admin route to create a post
POST http://localhost:3000/api/admin/create-post?password=password
Content-Type: application/json

{
  "project_id": 1,
  "topic_id": 1,
  "title": "Adding UPDATE statements",
  "draftContent": "<p>This is a post about the project.</p>"
}


### Update an existing post
PATCH http://localhost:3000/api/admin/update-post/1?password=password
Content-Type: application/json

{
  "post_id": 1,
  "project_id": 1,
  "title": "Updated Post Title",
  "draftContent": "<p>This is an updated post content.</p>"
}

### Get all posts
GET http://localhost:3000/api/posts